language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: GLzKbx79D4BWMj9BZAWUb2PjvfWhvxP9I9TkJ0KeJqZOdhZ4g4g2/jZj9KZWKBSUT8VBspQ/ZvYAjHOIAAdQakT9YpFcT5FopRb8zSEZJWtwvi0aqlC2PKwOqrrVHa4ogt0ojTNmhJcsuhQYcLfirzZTlo/iLqTLRVnvoydF1tVmqRIr4hpHnj7boF7sM8jQ3pKHR3AsZfruWbSMkSblC62dxR0Sx+3aBT76UW2RlrsevGWfvAYRpvVzPRTCSFmfJS+9Rzu7dEW1A0NzQxsGpuaGa7EK+VR4GzTsq9Yb+i+JJvAihHOT/PObiFxYjfIMmyCniq8etEsA8AGgQFEhpPf3OZJGx5OvBcVGBmTqGCJ7G5AlDxjiFw2H6l3PxDJoST7Bf4UskQpdTcNfCnpBSbxKRlBH6Qh0tGfUt3P2JSvDfLKLqeDad04Lj0qDBy7Ha1E7VMjIfRcs8Omf8KW3tYLSbhtwCoCLE1stFgpugTFB2qW3Y7chXSbe1Dm0wDsgyBUailBpSv5Yh88euLIdIBH2VHBg7wB+n51z0bsU27rB5ZhQLaehvKtakJCDviXfuZurlftBp0grNAjTWGISQMoVU/jKmNNwUJCopZYFDn+KP9qW+gXlV3FxD+StUtn1yNPjEOWK60JY375z9ZB8IEmciHHOkEYJ/bSeQs1bbhU=
